prog =
    | list(toplevel)

toplevel =
    | theorem
    | axiom
    | definition

theorem =
    | THEOREM GLOBAL LPAREN typed_parameter_list RPAREN COLON expression PROOF expression QED

axiom =
    | AXIOM GLOBAL LPAREN typed_parameter_list RPAREN COLON expression DONE

definition =
    | DEFINITION GLOBAL LPAREN

typed_parameter_list =
    | separated_list(COMMA, typed_parameter)

typed_parameter =
    | FREE COLON expression

untyped_parameter_list =
    | separated_list(COMMA, untyped_parameter)

untyped_parameter =
    | expression

expression =
    | instantiation
    | application
    | LAMBDA expression DOT expression
    | PI expression DOT expression

instantiation =
    | GLOBAL LPAREN argument_list RPAREN

argument_list =
    | separated_list(COMMA, expression)

application =
    | simple
    | application simple

simple =
    | LPAREN expression RPAREN
    | FREE
    | INDEX
